version: '3.1'

services:

  back:
    build: .docker/php
    container_name: back
    ports: 
      - "8000:80"
    volumes: 
      - ./movaTest:/var/www/html
    env_file:
           - ./movaTest/.env
    networks:
      - app    
    


  db:
    build: .docker/mysql
    container_name: db
    restart: always
    volumes:
      - "./.docker/dbdata:/var/lib/mysql"
    environment: 
      MYSQL_ROOT_PASSWORD: A_1234567
      MYSQL_DATABASE: laravel
    ports: 
      - "3307:3306"
    networks:
      - app      

  phpmyadmin: 
    image: phpmyadmin
    container_name: myadmin
    restart: always
    ports:
      - 8080:80
    networks:
      - app    

  pgdb:
    image: postgres
    container_name: pgdb
    environment:
    - POSTGRES_USER=admin
    - POSTGRES_PASSWORD=postgres   
    - POSTGRES_DB=postgres  
    ports:
    - "5432:5432"
    volumes:
    - ./.docker/pgdata:/var/lib/postgresql/data 
    networks:
    - app      

  pgadm:
    image: dpage/pgadmin4
    container_name: pgadm
    restart: always
    environment:
    - PGADMIN_DEFAULT_EMAIL=admin@admin.com
    - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
    - "5050:80"
    networks:
    - app    

networks:
  app:
    driver: bridge