version: "3.2"
services:
   php_app:
       build:
          context: .
          dockerfile: ./.docker/php/Dockerfile
       container_name: lara
       volumes:
           - ./lara:/var/www/html
       ports: 
       - "8000:80"
       env_file:
           - ./lara/.env
       networks:
       - app
     
   api_php:
       build:
          context: .
          dockerfile: ./.docker/php/Dockerfile
       container_name: api
       volumes:
           - ./api:/var/www/html
       ports: 
       - "4000:80"
       env_file:
           - ./api/.env
       networks:
       - app

   pgdb:
      image: postgres
      container_name: pgdb
      environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=postgres   
      - POSTGRES_DB=postgres  
      ports:
      - "5432:5432"
      volumes:
      - ./postgres:/data/postgres 
      networks:
      - app      

   pgadm:
    image: dpage/pgadmin4
    container_name: pgadm
    restart: always
    environment:
    - PGADMIN_DEFAULT_EMAIL=admin@admin.com
    - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
    - "5050:80"
    networks:
    - app    

networks:
  app:
    driver: bridge